name: Lint PHP

on:
    # Run on all relevant pushes and on all relevant pull requests.
    push:
        paths:
            - "**.php"
            - "composer.json"
            - "composer.lock"
            - "phpcs.xml"
            - "phpcs.xml.dist"
            - "phpstan.neon"
            - "phpstan.neon.dist"
            - "code-quality-php.yml"
    pull_request:
        paths:
            - "**.php"
            - "composer.json"
            - "composer.lock"
            - "phpcs.xml"
            - "phpcs.xml.dist"
            - "phpstan.neon"
            - "phpstan.neon.dist"
            - "code-quality-php.yml"
    # Allow manually triggering the workflow.
    workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name.
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php_version: ["8.1","8.2", "8.3", "8.4"]

        name: "Lint: PHP ${{ matrix.php_version }}"

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Check Code Quality
              uses: ./.github/actions/code-quality
              with:
                  php-version: ${{ matrix.php_version }}

