name: Deploy to WordPress.org

on:
    release:
        types: [ published ]

jobs:
    new-release:
        name: New release
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            # Build Plugin (NPM, Composer Dependencies)
            -   name: Build
                id: build-plugin
                uses: ./.github/actions/build-plugin

            # Uses .distignore
            -   name: WordPress Plugin Deploy
                id: deploy
                uses: 10up/action-wordpress-plugin-deploy@1.5.0
                env:
                    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                    SLUG: sharable-password-protected-posts
